### ISSUE TITLE
Strange change file name after upload

### ISSUE THREAD

**Issue by sarak** [mariuswilms/media#39]
Hi.
I moved my application form development server to production.
I upload file and it was saved with strange name.
For example i put in upload form "image1.jpg", 
its base name in mysql in basename column i see "m.p".
On disk it saved as /media/transfer/img/m.p . (?!)
Which function generete basename after upload?

lightbox-btn-close.gif ->  l_t_o_t_lo
image1.jpg -> m.p
thumb_image4.jpg -> t_um_m.p

(version 0.6)

**Comment by AD7six** [comment]
This isn't media specific.

If you've got that problem it's because Inflector::slug isn't working correctly (because of broken or disabled utf8 regex support) the consequences of which are pretty significant as it'll mean, amongst other problems, that most model validation passes/fails when it shouldn't and cache confusion occurs (looking for x, and getting back y from the cache as a "valid" result).

Here's a google search to get you going on how to fix (or at least identify) your problem http://www.google.es/search?sourceid=chrome&ie=UTF-8&q=cakephp+centos+slug

but again: it's not a media specific bug.

**Comment by mariuswilms** [comment]
Thanks AD7six for clearing that up :), closing this ticket.
