### ISSUE TITLE
performance issues with element

### ISSUE THREAD

**Issue by bazz-** [mariuswilms/media#42]
By performing 

$Media = Media::factory($file);

there is a huge slowdown when there are several larger attachments available (up to 1 minute). 

Debugging shows that gs (ghostscript) is generating thumbnails for the pdf files every time the statement above is called from within the attachment element.

Commenting out that line results in the file type (document/image) not showing, and also Undefined variable: Media - but it works.

**Comment by mariuswilms** [comment]
The usage of the Media class in the element was a relict from before the Media_Proces/Info refactor. I've updated the element so that it uses the name method exposed through the helper. This should fix the cause of the problem. 

However gs shouldn't ever be invoked are you sure it was originating from the element? Can you post a debug trace showing the problem?

**Comment by bazz-** [comment]
Hi david, sorry but I don't know how to debug such a thing.  I just created a bash script and looped a ps aux |grep nobody into a file. I can send that if you would like that.  alsothe test pdf files .
or if you can tell me how todebug it I'll do so.
thanks

**Comment by mariuswilms** [comment]
I can't replicate this behavior. 

This could as well have something to do with the meta behavior which can cause slowdowns when the cache is cold and huge PDFs need to be scanned. At least it reminds me of this. The solution is to lower the metadata level or remove the info adapter for documents.
