### ISSUE TITLE
Cake 2.0 Version

### ISSUE THREAD

**Issue by ReplicaObscura** [mariuswilms/media#66]
I just wanted to let you know that I have started a CakePHP 2.0 port of the Media plugin. I wasn't sure if you had plans for starting a branch for CakePHP 2.0 or not. If so--feel free to merge my branch, or to cherry-pick any code you'd like to use from it.

Here's my current version: https://github.com/bmcclure/CakePHP-Media-Plugin

I'm not sure validation is working properly just yet, and I haven't updated the tests, but everything else is working great now after some semi-extensive debugging in my 2.0 environment.

Oh, and as an added bonus, I have fixed all Windows issues--I am actually developing this 2.0 branch on Windows so I know it works great so far. As you hinted at, the biggest change required was to add the Media library to the beginning of the PATH, instead of at the end. Then it just needed minor bug fixes that may have either been related to the switch to Cake 2.0, or to being on Windows.

If you do merge the branch or start your own branch, I would be happy to help out wherever I can.

Thanks!

**Comment by tfiersen** [comment]
Nice, i was about to start something similar because i'm now switching to Cake 2.0 and i couldn't live without the Media plugin :)

**Comment by ReplicaObscura** [comment]
I've gotten almost everything working perfectly in the 2.0 version, and I've even added a couple of features so far (such as using named and/or per-model Generator filters, instead of just a single shared filter set).

Until such time as David decides to merge the 2.0 branch into his (assuming he wants to at all), I've posted a Wiki and Issues section at my branch's page, if you have any issues specific to the 2.0 version.

**Comment by mariuswilms** [comment]
I'd be open for a 2.0 compatible version of the plugin. The plugin was originally born out of necessity for http://npiece.com. So that always has been my use case. Now things are a little different I don't currently have a cake2 project cooking and have less time (I know). 

However I see that a 2.0 version would be just the next thing to do and as @tfiersen mentioned possibly a lot of users don't want and shouldn't need to drop usage of the plugin while transitioning to cake2. My idea for a take on this is that I'll be first trying to get the final version of 1.3 out the door, than also closely looking what for example @bmcclure (thanks for the work) or anybody else dedicating time on this does. 

I already have the next version of the plugin prepared, which will update the codebase i.e. to use PHP5 visibility on methods and properties. This would probably be a good candidate for rebasing the changes out there on. 

I'll try to organize this step to 2.0.

**Comment by ReplicaObscura** [comment]
Thanks, David!

That sounds great--when you've posted a 'final' version of 1.3, I would also be very happy to update my 2.0 branch to utilize your latest changes, if that might help.

**Comment by ReplicaObscura** [comment]
Sorry, closed by accident :)
