### ISSUE TITLE
Incorrect $this->_versions array in medium helper

### ISSUE THREAD

**Issue by snowdog** [mariuswilms/media#9]
Array generated from Media.filter in __construct is incorrect, merges values from all attachments types

**Comment by mariuswilms** [comment]
This is the intended behavior, why do you think this could be incorrect?

**Comment by snowdog** [comment]
Because the array looks like this (using default config):
Array
(
    [0] => s
    [1] => m
    [2] => m
    [3] => m
    [4] => l
    [5] => xl
)

So filters xs and xxs can't be displayed

**Comment by mariuswilms** [comment]
I cannot reproduce the issue you are experiencing. I've just added a test (f2796ba049fd397b0645baac33ea66a87cfaca5f) which runs fine. Please run the medium helper test yourself and see if it fails for you or provide a failing test case. This way I could reproduce the issue.

**Comment by snowdog** [comment]
The test you provided fails on line 103 (not equal). Probably the problem is the PHP version (I use 5.2.6).

**Comment by mariuswilms** [comment]
I've tested with 5.2.10 and 5.3.0. In both cases the test passes for me. The problem is if I cannot reproduce the problem you're experiencing I cannot fix it. This is because I would not be able to prove that the "fix" actually fixed the problem.
A solution would be if you could suggest a fix (by providing a patch) which fixes the problem for you.
